# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/Laura/OneDrive/Documents/1_Studium/Sem8_SS22/Fortgeschrittenenpraktikum/unsergit_clone/PraktikumEV

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/laura/OneDrive/Documents/1_Studium/Sem8_SS22/Fortgeschrittenenpraktikum/unsergit_clone/PraktikumEV

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/laura/OneDrive/Documents/1_Studium/Sem8_SS22/Fortgeschrittenenpraktikum/unsergit_clone/PraktikumEV/CMakeFiles /mnt/c/Users/laura/OneDrive/Documents/1_Studium/Sem8_SS22/Fortgeschrittenenpraktikum/unsergit_clone/PraktikumEV/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/laura/OneDrive/Documents/1_Studium/Sem8_SS22/Fortgeschrittenenpraktikum/unsergit_clone/PraktikumEV/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named indent

# Build rule for target.
indent: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 indent
.PHONY : indent

# fast build rule for target.
indent/fast:
	$(MAKE) -f CMakeFiles/indent.dir/build.make CMakeFiles/indent.dir/build
.PHONY : indent/fast

#=============================================================================
# Target rules for targets named praktikum.g

# Build rule for target.
praktikum.g: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 praktikum.g
.PHONY : praktikum.g

# fast build rule for target.
praktikum.g/fast:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/build
.PHONY : praktikum.g/fast

#=============================================================================
# Target rules for targets named praktikum

# Build rule for target.
praktikum: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 praktikum
.PHONY : praktikum

# fast build rule for target.
praktikum/fast:
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/build
.PHONY : praktikum/fast

#=============================================================================
# Target rules for targets named gtests.g

# Build rule for target.
gtests.g: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtests.g
.PHONY : gtests.g

# fast build rule for target.
gtests.g/fast:
	$(MAKE) -f gtests/CMakeFiles/gtests.g.dir/build.make gtests/CMakeFiles/gtests.g.dir/build
.PHONY : gtests.g/fast

#=============================================================================
# Target rules for targets named gtests

# Build rule for target.
gtests: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gtests
.PHONY : gtests

# fast build rule for target.
gtests/fast:
	$(MAKE) -f gtests/CMakeFiles/gtests.dir/build.make gtests/CMakeFiles/gtests.dir/build
.PHONY : gtests/fast

source/dummy.o: source/dummy.cc.o

.PHONY : source/dummy.o

# target to build an object file
source/dummy.cc.o:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/source/dummy.cc.o
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/source/dummy.cc.o
.PHONY : source/dummy.cc.o

source/dummy.i: source/dummy.cc.i

.PHONY : source/dummy.i

# target to preprocess a source file
source/dummy.cc.i:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/source/dummy.cc.i
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/source/dummy.cc.i
.PHONY : source/dummy.cc.i

source/dummy.s: source/dummy.cc.s

.PHONY : source/dummy.s

# target to generate assembly for a file
source/dummy.cc.s:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/source/dummy.cc.s
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/source/dummy.cc.s
.PHONY : source/dummy.cc.s

source/dummy2.o: source/dummy2.cc.o

.PHONY : source/dummy2.o

# target to build an object file
source/dummy2.cc.o:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/source/dummy2.cc.o
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/source/dummy2.cc.o
.PHONY : source/dummy2.cc.o

source/dummy2.i: source/dummy2.cc.i

.PHONY : source/dummy2.i

# target to preprocess a source file
source/dummy2.cc.i:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/source/dummy2.cc.i
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/source/dummy2.cc.i
.PHONY : source/dummy2.cc.i

source/dummy2.s: source/dummy2.cc.s

.PHONY : source/dummy2.s

# target to generate assembly for a file
source/dummy2.cc.s:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/source/dummy2.cc.s
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/source/dummy2.cc.s
.PHONY : source/dummy2.cc.s

source/helpfunctions.o: source/helpfunctions.cc.o

.PHONY : source/helpfunctions.o

# target to build an object file
source/helpfunctions.cc.o:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/source/helpfunctions.cc.o
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/source/helpfunctions.cc.o
.PHONY : source/helpfunctions.cc.o

source/helpfunctions.i: source/helpfunctions.cc.i

.PHONY : source/helpfunctions.i

# target to preprocess a source file
source/helpfunctions.cc.i:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/source/helpfunctions.cc.i
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/source/helpfunctions.cc.i
.PHONY : source/helpfunctions.cc.i

source/helpfunctions.s: source/helpfunctions.cc.s

.PHONY : source/helpfunctions.s

# target to generate assembly for a file
source/helpfunctions.cc.s:
	$(MAKE) -f CMakeFiles/praktikum.g.dir/build.make CMakeFiles/praktikum.g.dir/source/helpfunctions.cc.s
	$(MAKE) -f CMakeFiles/praktikum.dir/build.make CMakeFiles/praktikum.dir/source/helpfunctions.cc.s
.PHONY : source/helpfunctions.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... test"
	@echo "... indent"
	@echo "... praktikum.g"
	@echo "... praktikum"
	@echo "... gtests.g"
	@echo "... gtests"
	@echo "... source/dummy.o"
	@echo "... source/dummy.i"
	@echo "... source/dummy.s"
	@echo "... source/dummy2.o"
	@echo "... source/dummy2.i"
	@echo "... source/dummy2.s"
	@echo "... source/helpfunctions.o"
	@echo "... source/helpfunctions.i"
	@echo "... source/helpfunctions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

