ARPACK++: /home/purusharth/Documents/sem4/eigen-prakitum/sandbox/PraktikumEV/include/standard_include.hh File Reference
standard_include.hh File Reference
#include <cassert>
#include <cinttypes>
#include <cmath>
#include <iostream>
#include <string>
#include <vector>
#include <list>
#include <unordered_set>
#include <map>
#include <unordered_map>
Macros
#define mos std::cout << __FILE__ << ":" << __LINE__ << ": "
#define PRINT_REFLECTION(X) #X << ": " << X
Typedefs
using byte_t = uint8_t
Functions
template<typename TFirst , typename TSecond >
std::ostream & operator<< (std::ostream &os, const std::pair< TFirst, TSecond > &P)
template<typename TContainerIter >
std::ostream & __CONTAINER_ITER_PRINT (std::ostream &os, TContainerIter beginiter, TContainerIter enditer)
template<typename TContainer >
std::ostream & __CONTAINER_PRINT (std::ostream &os, const TContainer &C)
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::vector< T > &V)
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::list< T > &V)
template<typename T >
std::ostream & operator<< (std::ostream &os, const std::unordered_set< T > &S)
template<typename T1 , typename T2 >
std::ostream & operator<< (std::ostream &os, const std::map< T1, T2 > &M)
template<typename T1 , typename T2 >
std::ostream & operator<< (std::ostream &os, const std::unordered_map< T1, T2 > &M)
Macro Definition Documentation
mos
#define mos std::cout << __FILE__ << ":" << __LINE__ << ": "
Definition at line 60 of file standard_include.hh.
PRINT_REFLECTION
#define PRINT_REFLECTION (X) #X << ": " << X
Definition at line 62 of file standard_include.hh.
Typedef Documentation
byte_t
using byte_t = uint8_t
Definition at line 65 of file standard_include.hh.
Function Documentation
__CONTAINER_ITER_PRINT()
template<typename TContainerIter > std::ostream& __CONTAINER_ITER_PRINT (std::ostream & os, TContainerIter beginiter, TContainerIter enditer)
Definition at line 78 of file standard_include.hh.
Referenced by __CONTAINER_PRINT().
__CONTAINER_PRINT()
template<typename TContainer > std::ostream& __CONTAINER_PRINT (std::ostream & os, const TContainer & C)
Definition at line 93 of file standard_include.hh.
References __CONTAINER_ITER_PRINT().
Referenced by operator<<().
operator<<() [1/6]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::list< T > & V)
Definition at line 107 of file standard_include.hh.
References __CONTAINER_PRINT().
operator<<() [2/6]
template<typename T1 , typename T2 > std::ostream& operator<< (std::ostream & os, const std::map< T1, T2 > & M)
Definition at line 119 of file standard_include.hh.
References __CONTAINER_PRINT().
operator<<() [3/6]
template<typename TFirst , typename TSecond > std::ostream& operator<< (std::ostream & os, const std::pair< TFirst, TSecond > & P)
Definition at line 71 of file standard_include.hh.
operator<<() [4/6]
template<typename T1 , typename T2 > std::ostream& operator<< (std::ostream & os, const std::unordered_map< T1, T2 > & M)
Definition at line 125 of file standard_include.hh.
References __CONTAINER_PRINT().
operator<<() [5/6]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::unordered_set< T > & S)
Definition at line 113 of file standard_include.hh.
References __CONTAINER_PRINT().
operator<<() [6/6]
template<typename T > std::ostream& operator<< (std::ostream & os, const std::vector< T > & V)
Definition at line 100 of file standard_include.hh.
References __CONTAINER_PRINT().